#!/bin/sh

# Set these paths appropriately

BIN="/home/ken/Gandalf/name-entity-recognition-multi/SRC/fr-tag/bin"
CMD="/home/ken/Gandalf/name-entity-recognition-multi/SRC/fr-tag/cmd"
LIB="/home/ken/Gandalf/name-entity-recognition-multi/SRC/fr-tag/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
