#!/bin/sh

# Set these paths appropriately

BIN="/home/ken/Gandalf/name-entity-recognition-multi/SRC/fr-tag/bin"
CMD="/home/ken/Gandalf/name-entity-recognition-multi/SRC/fr-tag/cmd"
LIB="/home/ken/Gandalf/name-entity-recognition-multi/SRC/fr-tag/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
