#!/bin/sh

# Set these paths appropriately

BIN="/home/ken/Gandalf/name-entity-recognition-multi/SRC/fr-tag/bin"
CMD="/home/ken/Gandalf/name-entity-recognition-multi/SRC/fr-tag/cmd"
LIB="/home/ken/Gandalf/name-entity-recognition-multi/SRC/fr-tag/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
TAGGER=tree-tagger
ABBR_LIST=${LIB}/portuguese-abbreviations
PARFILE=${LIB}/portuguese2.par

$TOKENIZER -p -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
