#!/bin/sh

# Set these paths appropriately

BIN="/home/oscar/MALV/name-entity-recognition-multi/TAGGERS/bin"
CMD="/home/oscar/MALV/name-entity-recognition-multi/TAGGERS/cmd"
LIB="/home/oscar/MALV/name-entity-recognition-multi/TAGGERS/lib"

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/german-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german-spoken.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
