#!/bin/sh

# Set these paths appropriately

BIN="/home/oscar/MALV/name-entity-recognition-multi/TAGGERS/bin"
CMD="/home/oscar/MALV/name-entity-recognition-multi/TAGGERS/cmd"
LIB="/home/oscar/MALV/name-entity-recognition-multi/TAGGERS/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/catalan-abbreviations
PARFILE=${LIB}/catalan.par

$TOKENIZER -c -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
