#!/bin/sh

# Set these paths appropriately

BIN="/home/oscar/MALV/name-entity-recognition-multi/TAGGERS/bin"
CMD="/home/oscar/MALV/name-entity-recognition-multi/TAGGERS/cmd"
LIB="/home/oscar/MALV/name-entity-recognition-multi/TAGGERS/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
